---
- name: Create Intersight Link Control Policy
  hosts: localhost
  gather_facts: no
  vars:
    api_private_key: "C:\\secretKey.txt"
    api_key_id: "xxxxx27564612d30dxxxxx/5f21c9d97564612d30dd575a/5f9a8b877564612xxxxxxxx"
    organization: "default"

  tasks:
    - name: Create link control policy 
      cisco.intersight.intersight_link_control_policy:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        organization: "{{ organization }}"
        name: test_link_control_policy
        description: "Test link control policy description"
        tags:
          - Key: Site
            Value: Test
          - Key: Site2
            Value: Test2
        udld_admin_state: "Enabled"
        udld_mode: "normal"
      check_mode: true
      register: creation_res_check_mode