---
- name: Create Intersight Multicast Policy
  hosts: localhost
  gather_facts: no
  vars:
    api_private_key: "/root/secretKey.txt"
    api_key_id: "xxxxx27564612d30dxxxxx/5f21c9d97564612d30dd575a/5f9a8b877564612xxxxxxxx"
    organization: "default"

  tasks:
    - name: Create Multicast policy
      cisco.intersight.intersight_multicast_policy:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        organization: "{{ organization }}"
        name: "test_multicast_policy"
        description: "Test Multicast policy created with Ansible"
        querier_ip_address: "192.168.0.1"
        querier_state: "Enabled"
        snooping_state: "Enabled"
        tags:
          - Key: "Site"
            Value: "RCDN"