---
# Example Playbook: cisco.intersight.intersight_bios_policy
# Author: Jindat Baradia (@jingiris)
---
- name: Create Intersight BIOS Policy
  hosts: localhost
  gather_facts: no
  vars:
    api_private_key: "C:\\secretKey.txt"
    api_key_id: "xxxxx27564612d30dxxxxx/5f21c9d97564612d30dd575a/5f9a8b877564612xxxxxxxx"
    organization: "default"

  tasks:
    - name: Configure BIOS Policy
      cisco.intersight.intersight_bios_policy:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        organization: "{{ organization }}"
        name: BIOS
        description: Boot Order policy
        tags:
          - Key: Site
            Value: RCDN
        processor_cstate: enabled